# Generated by Django 5.2.7 on 2025-10-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre_producto'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_imagen',
            field=models.CharField(blank=True, help_text='Nombre del archivo de imagen en la carpeta imagenes_productos', max_length=255, null=True),
        ),
    ]
