# Generated by Django 5.2.7 on 2025-10-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_options_remove_producto_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='nombre_imagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
